### ISSUE TITLE
undefined method `to_ios' 

### ISSUE THREAD

**Issue by guinslym** [asciidoctor/asciidoctor-epub3#135]
```
asciidoctor-epub3 -D chapitre1.epub chapitre1.adoc 
undefined method `to_ios' for #<Asciidoctor::Epub3::Packager:0x005625a8690ef0>
  Use --trace for backtrace
```

trace

```
[guinslym@readthedoc komsemne]$ asciidoctor-epub3 -D chapitre1.epub chapitre1.adoc  --trace
/home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3/packager.rb:438:in `postprocess_xhtml': undefined method `to_ios' for #<Asciidoctor::Epub3::Packager:0x005612f79cc678> (NoMethodError)
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3/packager.rb:280:in `block (3 levels) in add_content'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3/packager.rb:279:in `each'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3/packager.rb:279:in `each_with_index'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3/packager.rb:279:in `block (2 levels) in add_content'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:40:in `instance_eval'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:40:in `block in ordered'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/gepub-0.6.9.2/lib/gepub/package.rb:166:in `ordered'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/gepub-0.6.9.2/lib/gepub/book.rb:205:in `ordered'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:39:in `ordered'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3/packager.rb:276:in `block in add_content'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:33:in `instance_eval'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:33:in `initialize'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/gepub-0.6.9.2/lib/gepub/builder.rb:292:in `new'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/gepub-0.6.9.2/lib/gepub/builder.rb:292:in `resources'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3/packager.rb:271:in `add_content'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3/packager.rb:574:in `block in package'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/gepub-0.6.9.2/lib/gepub/builder.rb:185:in `instance_eval'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/gepub-0.6.9.2/lib/gepub/builder.rb:185:in `initialize'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3/packager.rb:488:in `new'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3/packager.rb:488:in `package'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3/converter.rb:41:in `write'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/asciidoctor-1.5.6.1/lib/asciidoctor/document.rb:1083:in `write'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1507:in `convert'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575:in `block in convert_file'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575:in `open'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575:in `convert_file'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/invoker.rb:108:in `block in invoke!'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/invoker.rb:102:in `each'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/invoker.rb:102:in `invoke!'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/gems/asciidoctor-epub3-1.5.0.alpha.7/bin/asciidoctor-epub3:32:in `<top (required)>'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/bin/asciidoctor-epub3:23:in `load'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/bin/asciidoctor-epub3:23:in `<main>'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from /home/guinslym/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by mojavelinux** [comment]
Can you please verify that your book adheres to the following structure rules?

https://github.com/asciidoctor/asciidoctor-epub3#structuring-your-manuscript

**Comment by guinslym** [comment]
thanks @mojavelinux! I didn't follow this guideline.
