### ISSUE TITLE
barfs on image example

### ISSUE THREAD

**Issue by jnavila** [asciidoctor/asciidoctor-epub3#140]
Trying to add xref anchors to images, I stumbled upon this bug.

With a simple structure as:

```
= Title

.A mountain sunset
[#img-sunset]
[caption="Figure 1: ",link=http://www.flickr.com/photos/javh/5448336655]
image::sunset.jpg[Sunset,300,200]
```

And an existing file `sunset.jpg`, the output is 

```
$ asciidoctor-epub3 --trace test.asc
/home/jnavila/.rvm/gems/ruby-2.4.0/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/document.rb:44: warning: constant ::Fixnum is deprecated
/home/jnavila/.rvm/gems/ruby-2.4.0/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3/packager.rb:438:in `postprocess_xhtml': undefined method `to_ios' for #<Asciidoctor::Epub3::Packager:0x0055bfcb709230> (NoMethodError)
Did you mean?  to_s
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3/packager.rb:280:in `block (3 levels) in add_content'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3/packager.rb:279:in `each'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3/packager.rb:279:in `each_with_index'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3/packager.rb:279:in `block (2 levels) in add_content'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:40:in `instance_eval'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:40:in `block in ordered'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/gepub-0.6.9.2/lib/gepub/package.rb:166:in `ordered'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/gepub-0.6.9.2/lib/gepub/book.rb:205:in `ordered'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:39:in `ordered'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3/packager.rb:276:in `block in add_content'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:33:in `instance_eval'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:33:in `initialize'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/gepub-0.6.9.2/lib/gepub/builder.rb:292:in `new'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/gepub-0.6.9.2/lib/gepub/builder.rb:292:in `resources'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3/packager.rb:271:in `add_content'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3/packager.rb:574:in `block in package'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/gepub-0.6.9.2/lib/gepub/builder.rb:185:in `instance_eval'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/gepub-0.6.9.2/lib/gepub/builder.rb:185:in `initialize'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3/packager.rb:488:in `new'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3/packager.rb:488:in `package'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3/converter.rb:41:in `write'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/document.rb:1083:in `write'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1507:in `convert'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575:in `block in convert_file'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575:in `open'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575:in `convert_file'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/invoker.rb:108:in `block in invoke!'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/invoker.rb:102:in `each'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/invoker.rb:102:in `invoke!'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/gems/asciidoctor-epub3-1.5.0.alpha.7/bin/asciidoctor-epub3:32:in `<top (required)>'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/bin/asciidoctor-epub3:23:in `load'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/bin/asciidoctor-epub3:23:in `<main>'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
        from /home/jnavila/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by mojavelinux** [comment]
This is the same as #47. Asciidoctor EPUB3 can only process an AsciiDoc document if it is structured as defined in the README. See https://github.com/asciidoctor/asciidoctor-epub3#structuring-your-manuscript

There are reasons for this limitation, but we plan to find a way to remove it.

**Comment by mojavelinux** [comment]
(the main reason is that it's how Asciidoctor EPUB3 knows where the boundaries of chapters are).

**Comment by jnavila** [comment]
OK. So, I'll open another issue. If you include this file into another and compile it, the image is does not retain the id attribute.

**Comment by mojavelinux** [comment]
Thanks. I'll have a look!
