### ISSUE TITLE
NoMethodError: undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by deoren** [asciidoctor/asciidoctor-epub3#156]
I received that error when attempting to build the Pro Git Second Edition epub file. Please let me know if I can supply additional information.

Distro: Ubuntu 17.10 x64

I tested on two different PCs, an older system and a newer one. I only encountered issues on the older PC.

The same version of VMware Workstation and Ubuntu guest OS was used with both.

## Steps to reproduce

1. `git clone https://github.com/progit/progit2.git`
1. `cd progit2/`
1. `git checkout rework_files` (progit/progit2#966)
1. `bundle install --path vendor/bundle`
1. `bundle exec asciidoctor-epub3 progit.asc`

## Gemfile

`ubuntu@ubuntu-devbox:/tmp/progit2$ cat Gemfile`

```
source 'https://rubygems.org'

gem 'rake'
gem 'asciidoctor', '1.5.6.1'

gem 'json'
gem 'awesome_print'

gem 'asciidoctor-epub3', :git => 'https://github.com/asciidoctor/asciidoctor-epub3'
gem 'asciidoctor-pdf', '1.5.0.alpha.16'

gem 'coderay'
gem 'pygments.rb'
gem 'thread_safe'
gem 'epubcheck'
gem 'kindlegen'
```

## Bundle list

`ubuntu@ubuntu-devbox:/tmp/progit2$ bundle list`

```
Gems included by the bundle:
  * Ascii85 (1.0.3)
  * addressable (2.5.2)
  * afm (0.2.2)
  * asciidoctor (1.5.6.1)
  * asciidoctor-epub3 (1.5.0.alpha.8.dev 752dac1)
  * asciidoctor-pdf (1.5.0.alpha.16)
  * awesome_print (1.8.0)
  * bundler (1.15.1)
  * coderay (1.1.2)
  * css_parser (1.6.0)
  * epubcheck (3.0.1)
  * gepub (0.6.9.2)
  * hashery (2.1.2)
  * json (2.1.0)
  * kindlegen (3.0.3)
  * mini_portile2 (2.1.0)
  * multi_json (1.13.1)
  * nokogiri (1.6.8.1)
  * pdf-core (0.7.0)
  * pdf-reader (2.0.0)
  * polyglot (0.3.5)
  * prawn (2.2.2)
  * prawn-icon (1.3.0)
  * prawn-svg (0.27.1)
  * prawn-table (0.2.2)
  * prawn-templates (0.1.1)
  * public_suffix (3.0.1)
  * pygments.rb (1.2.1)
  * rake (12.3.0)
  * ruby-rc4 (0.1.5)
  * rubyzip (1.2.1)
  * safe_yaml (1.0.4)
  * thread_safe (0.3.6)
  * treetop (1.5.3)
  * ttfunk (1.5.1)
```

## Bundle install

`ubuntu@ubuntu-devbox:/tmp/progit2$ bundle install --path vendor/bundle`

```
Fetching https://github.com/asciidoctor/asciidoctor-epub3
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Fetching rake 12.3.0
Installing rake 12.3.0
Fetching asciidoctor 1.5.6.1
Installing asciidoctor 1.5.6.1
Fetching json 2.1.0
Installing json 2.1.0 with native extensions
Fetching awesome_print 1.8.0
Installing awesome_print 1.8.0
Fetching mini_portile2 2.1.0
Installing mini_portile2 2.1.0
Fetching rubyzip 1.2.1
Installing rubyzip 1.2.1
Fetching thread_safe 0.3.6
Installing thread_safe 0.3.6
Fetching pdf-core 0.7.0
Installing pdf-core 0.7.0
Fetching ttfunk 1.5.1
Installing ttfunk 1.5.1
Fetching public_suffix 3.0.1
Installing public_suffix 3.0.1
Fetching Ascii85 1.0.3
Installing Ascii85 1.0.3
Fetching afm 0.2.2
Installing afm 0.2.2
Fetching hashery 2.1.2
Installing hashery 2.1.2
Fetching ruby-rc4 0.1.5
Installing ruby-rc4 0.1.5
Fetching safe_yaml 1.0.4
Installing safe_yaml 1.0.4
Fetching polyglot 0.3.5
Installing polyglot 0.3.5
Fetching coderay 1.1.2
Installing coderay 1.1.2
Fetching multi_json 1.13.1
Installing multi_json 1.13.1
Fetching epubcheck 3.0.1
Installing epubcheck 3.0.1
Using bundler 1.15.1
Fetching nokogiri 1.6.8.1
Installing nokogiri 1.6.8.1 with native extensions
Fetching kindlegen 3.0.3
Installing kindlegen 3.0.3 with native extensions
Fetching prawn 2.2.2
Installing prawn 2.2.2
Fetching addressable 2.5.2
Installing addressable 2.5.2
Fetching pdf-reader 2.0.0
Installing pdf-reader 2.0.0
Fetching treetop 1.5.3
Installing treetop 1.5.3
Fetching pygments.rb 1.2.1
Installing pygments.rb 1.2.1
Fetching gepub 0.6.9.2
Installing gepub 0.6.9.2
Fetching prawn-icon 1.3.0
Installing prawn-icon 1.3.0
Fetching prawn-table 0.2.2
Installing prawn-table 0.2.2
Fetching css_parser 1.6.0
Installing css_parser 1.6.0
Fetching prawn-templates 0.1.1
Installing prawn-templates 0.1.1
Using asciidoctor-epub3 1.5.0.alpha.8.dev from https://github.com/asciidoctor/asciidoctor-epub3 (at master@752dac1)
Fetching prawn-svg 0.27.1
Installing prawn-svg 0.27.1
Fetching asciidoctor-pdf 1.5.0.alpha.16
Installing asciidoctor-pdf 1.5.0.alpha.16
Bundle complete! 11 Gemfile dependencies, 35 gems now installed.
Bundled gems are installed into ./vendor/bundle.
```

## Normal build attempt

`bundle exec asciidoctor-epub3 progit.asc`

```
undefined method `split' for nil:NilClass
  Use --trace for backtrace
```

## Build with --trace option

`ubuntu@ubuntu-devbox:/tmp/progit2$ bundle exec asciidoctor-epub3 progit.asc --trace`

```
/tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/substitutors.rb:139:in `apply_subs': undefined method `split' for nil:NilClass (NoMethodError)
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/block.rb:118:in `content'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/bundler/gems/asciidoctor-epub3-752dac1b76fb/lib/asciidoctor-epub3/converter.rb:324:in `listing'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/bundler/gems/asciidoctor-epub3-752dac1b76fb/lib/asciidoctor-epub3/converter.rb:92:in `convert'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:70:in `convert'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:79:in `block in content'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:79:in `map'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:79:in `content'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/bundler/gems/asciidoctor-epub3-752dac1b76fb/lib/asciidoctor-epub3/converter.rb:207:in `section'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/bundler/gems/asciidoctor-epub3-752dac1b76fb/lib/asciidoctor-epub3/converter.rb:92:in `convert'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:70:in `convert'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:79:in `block in content'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:79:in `map'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:79:in `content'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/bundler/gems/asciidoctor-epub3-752dac1b76fb/lib/asciidoctor-epub3/converter.rb:207:in `section'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/bundler/gems/asciidoctor-epub3-752dac1b76fb/lib/asciidoctor-epub3/converter.rb:92:in `convert'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:70:in `convert'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:79:in `block in content'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:79:in `map'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:79:in `content'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/document.rb:1120:in `content'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/bundler/gems/asciidoctor-epub3-752dac1b76fb/lib/asciidoctor-epub3/converter.rb:124:in `document'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/bundler/gems/asciidoctor-epub3-752dac1b76fb/lib/asciidoctor-epub3/converter.rb:92:in `convert'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/document.rb:1060:in `convert'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/bundler/gems/asciidoctor-epub3-752dac1b76fb/lib/asciidoctor-epub3/packager.rb:292:in `block (3 levels) in add_content'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/bundler/gems/asciidoctor-epub3-752dac1b76fb/lib/asciidoctor-epub3/packager.rb:291:in `each'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/bundler/gems/asciidoctor-epub3-752dac1b76fb/lib/asciidoctor-epub3/packager.rb:291:in `each_with_index'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/bundler/gems/asciidoctor-epub3-752dac1b76fb/lib/asciidoctor-epub3/packager.rb:291:in `block (2 levels) in add_content'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:40:in `instance_eval'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:40:in `block in ordered'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/gepub-0.6.9.2/lib/gepub/package.rb:166:in `ordered'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/gepub-0.6.9.2/lib/gepub/book.rb:205:in `ordered'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:39:in `ordered'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/bundler/gems/asciidoctor-epub3-752dac1b76fb/lib/asciidoctor-epub3/packager.rb:288:in `block in add_content'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:33:in `instance_eval'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:33:in `initialize'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/gepub-0.6.9.2/lib/gepub/builder.rb:292:in `new'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/gepub-0.6.9.2/lib/gepub/builder.rb:292:in `resources'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/bundler/gems/asciidoctor-epub3-752dac1b76fb/lib/asciidoctor-epub3/packager.rb:283:in `add_content'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/bundler/gems/asciidoctor-epub3-752dac1b76fb/lib/asciidoctor-epub3/packager.rb:591:in `block in package'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/gepub-0.6.9.2/lib/gepub/builder.rb:185:in `instance_eval'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/gepub-0.6.9.2/lib/gepub/builder.rb:185:in `initialize'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/bundler/gems/asciidoctor-epub3-752dac1b76fb/lib/asciidoctor-epub3/packager.rb:505:in `new'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/bundler/gems/asciidoctor-epub3-752dac1b76fb/lib/asciidoctor-epub3/packager.rb:505:in `package'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/bundler/gems/asciidoctor-epub3-752dac1b76fb/lib/asciidoctor-epub3/converter.rb:41:in `write'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/document.rb:1083:in `write'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1507:in `convert'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575:in `block in convert_file'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575:in `open'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575:in `convert_file'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/invoker.rb:108:in `block in invoke!'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/invoker.rb:102:in `each'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/invoker.rb:102:in `invoke!'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/bundler/gems/asciidoctor-epub3-752dac1b76fb/bin/asciidoctor-epub3:32:in `<top (required)>'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/bin/asciidoctor-epub3:22:in `load'
	from /tmp/progit2/vendor/bundle/ruby/2.3.0/bin/asciidoctor-epub3:22:in `<main>'
```

**Comment by mojavelinux** [comment]
I'm almost certain this is the same problem as https://github.com/asciidoctor/asciidoctor/issues/2341, which has been resolved in the upcoming Asciidoctor 1.5.7.

I made the assumption that pygments.rb would always return a string, but I've since learned there are cases when it can return nil.

**Comment by mojavelinux** [comment]
Can you try with Asciidoctor HEAD?

**Comment by deoren** [comment]
@mojavelinux Thanks for the reply. I should be able to test on the affected system later tonight and provide feedback then.

**Comment by deoren** [comment]
> @mojavelinux: Can you try with Asciidoctor HEAD?

That seems to have done the trick: It took a VERY long time to complete on my old system, but the epub file was successfully built.

**Comment by mojavelinux** [comment]
I'm glad to hear that fixed it.

Is it just as slow if you disable syntax highlighting? My guess is that it's the calls to Pygments that are slowing it down.

**Comment by deoren** [comment]
@mojavelinux My apologies, but I call myself looking and I don't see a way to turn that off. I see mention of specifying the highlighter in the document header and also via the `pygments-style` attribute (`asciidoctor-epub3 -a pygments-style=pastie`), but I don't see a flag to actually turn it off.

Would something like `asciidoctor-epub3 -a pygments-style=none` work?

**Comment by mojavelinux** [comment]
http://asciidoctor.org/docs/user-manual/#source-code-blocks

**Comment by deoren** [comment]
@mojavelinux Thanks for the link. I reviewed the page, but didn't see a way to disable the syntax highlighting from a user's point of view (someone who just wants to build the docs, not modify the documentation itself).

On a related note, the devs on the progit/progit2 repo had to revert back to 1.5.6.1 to resolve a regression in the formatting for internal linkage:

refs: https://github.com/progit/progit2/issues/966#issuecomment-362052242

I'll be happy to file a separate issue for this if you don't already have something for it.

**Comment by mojavelinux** [comment]
It's like this:

```
asciidoctor-epub3 -a source-highlighter! book.adoc
```

The `-a name!` unsets a document attribute from the cli.

**Comment by mojavelinux** [comment]
> On a related note, the devs on the progit/progit2 repo had to revert back to 1.5.6.1 to resolve a regression in the formatting for internal linkage

It's not a formatting issue. It's a reference resolution issue. File a new issue in asciidoctor-epub3 and we'll get it sorted it. But it could be a new requirement.

**Comment by deoren** [comment]
> @mojavelinux: It's like this:
> 
> `asciidoctor-epub3 -a source-highlighter! book.adoc`
> 
> The -a name! unsets a document attribute from the cli.

Thank you! Thanks also for your patience with my newbie questions.

I'll test again tonight to see if that makes a difference in the build time. If nothing else it will be nice to bring the ticket full circle with that info.

> @mojavelinux: It's not a formatting issue. It's a reference resolution issue. File a new issue in asciidoctor-epub3 and we'll get it sorted it. But it could be a new requirement.

I'll create a new issue for that, thanks.

**Comment by deoren** [comment]
There was a "slight" difference between leaving highlighting enabled and having it off. ;)

**Disabled**:

`/output/progit2 # time bundle exec asciidoctor-epub3 -a source-highlighter! progit.asc`

```
/output/progit2/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/document.rb:44: warning: constant ::Fixnum is deprecated
real	0m 3.59s
user	0m 2.62s
sys	0m 0.65s
```

**Enabled**:

`/output/progit2 # time bundle exec asciidoctor-epub3 progit.asc`

```
/output/progit2/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/document.rb:44: warning: constant ::Fixnum is deprecated
/output/progit2/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/document.rb:44: warning: constant ::Fixnum is deprecated
real	1h 55m 19s
user	1h 18m 03s
sys	36m 23.85s
```

**Comment by mojavelinux** [comment]
That is very strange indeed. Something is going on in the bridge to Pygments in pygments.rb for sure. It should never take that long. Using pygments for source highlighting on my machine takes ~ 3 seconds.

**Comment by mojavelinux** [comment]
I'm going to close this as it was addressed in core.
