### ISSUE TITLE
Asciidoctor-epub3 1.5.0.alpha.17 crashes with a backtrace - Errno::EISDIR: Is a directory @ io_fread

### ISSUE THREAD

**Issue by paulmcquad** [asciidoctor/asciidoctor-epub3#353]
I'm creating a book and a run the command (--trace to debug the problem):
`bundle exec asciidoctor-epub3 prokde.asc --trace`

I get this backtrace:

```
Errno::EISDIR: Is a directory @ io_fread - /home/gamer/Documents/Coding Files/GitLab/prokde/
  /usr/lib/ruby/gems/2.7.0/gems/gepub-1.0.11/lib/gepub/item.rb:147:in `read'
  /usr/lib/ruby/gems/2.7.0/gems/gepub-1.0.11/lib/gepub/item.rb:147:in `add_content'
  /usr/lib/ruby/gems/2.7.0/gems/gepub-1.0.11/lib/gepub/package.rb:173:in `add_item'
  /usr/lib/ruby/gems/2.7.0/gems/gepub-1.0.11/lib/gepub/book.rb:464:in `add_item_internal'
  /usr/lib/ruby/gems/2.7.0/gems/gepub-1.0.11/lib/gepub/book_add_item.rb:9:in `add_item'
  /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-epub3-1.5.0.alpha.17/lib/asciidoctor-epub3/converter.rb:1307:in `add_cover_image'
  /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-epub3-1.5.0.alpha.17/lib/asciidoctor-epub3/converter.rb:223:in `convert_document'
  /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-epub3-1.5.0.alpha.17/lib/asciidoctor-epub3/converter.rb:106:in `convert'
  /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:951:in `convert'
  /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:118:in `convert'
  /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `block in convert_file'
  /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `open'
  /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `convert_file'
  /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
  /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `each'
  /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `invoke!'
  /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-epub3-1.5.0.alpha.17/bin/asciidoctor-epub3:28:in `<top (required)>'
  /bin/asciidoctor-epub3:23:in `load'
  /bin/asciidoctor-epub3:23:in `<top (required)>
```

**Comment by slonopotamus** [comment]
What's the value of your `:front-cover-image:` attribute? I think it points to a directory instead of an image file.

**Comment by paulmcquad** [comment]
> What's the value of your `:front-cover-image:` attribute? I think it points to a directory instead of an image file.

slonopotamus that was it. The value wasn't set. I just removed the ':front-cover-image:' attribute from the file.
Maybe this is a small bug cause when i remove the attribute it builds but splits out a warning:
asciidoctor: WARNING: Warning(prcgen):W14016: Cover not specified

**Comment by slonopotamus** [comment]
I'll adjust code a bit so asciidoctor-epub3 doesn't crash with backtrace in this scenario. WRT a warning - it comes from [KindleGen](https://www.amazon.com/gp/feature.html?ie=UTF8&docId=1000765211), this is out of our control.
