### ISSUE TITLE
No implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by tkrop** [asciidoctor/asciidoctor-epub3#360]
Sorry that we do not have the time to investigate further: Since some unknown date between Jun 14 and July 30, we experience the following error running `docker run -v output:/documents/ asciidoctor/docker-asciidoctor asciidoctor-epub3 -D /documents/output index.adoc` on http://github.com/zalando/restful-api-guidelines (see also https://github.com/zalando/restful-api-guidelines/issues/597). It was working fine before and if we fallback to `asciidoctor/docker-asciidoctor:1.1.0` everything works fine again.

```
/usr/lib/ruby/gems/2.7.0/gems/asciidoctor-epub3-1.5.0.alpha.18/lib/asciidoctor-epub3/converter.rb:108:in `basename': no implicit conversion of nil into String (TypeError)
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-epub3-1.5.0.alpha.18/lib/asciidoctor-epub3/converter.rb:108:in `convert'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-epub3-1.5.0.alpha.18/lib/asciidoctor-epub3/converter.rb:454:in `convert_section'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-epub3-1.5.0.alpha.18/lib/asciidoctor-epub3/converter.rb:106:in `convert'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:1020:in `content'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-epub3-1.5.0.alpha.18/lib/asciidoctor-epub3/converter.rb:359:in `add_chapter'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-epub3-1.5.0.alpha.18/lib/asciidoctor-epub3/converter.rb:250:in `convert_document'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-epub3-1.5.0.alpha.18/lib/asciidoctor-epub3/converter.rb:106:in `convert'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:951:in `convert'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:118:in `convert'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `block in convert_file'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `open'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `convert_file'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `each'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `invoke!'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-epub3-1.5.0.alpha.18/bin/asciidoctor-epub3:28:in `<top (required)>'
	from /usr/bin/asciidoctor-epub3:23:in `load'
	from /usr/bin/asciidoctor-epub3:23:in `<main>'
```

May be you have an idea what changed and how to fix this.

**Comment by slonopotamus** [comment]
1. Your document has inline `toc::[]` macro that we don't support (#344)
2. We failed to report a warning about that (will fix separately)

**Comment by slonopotamus** [comment]
As a workaround, hide `toc::[]` macro from asciidoctor-epub3 via `ifndef::ebook-format`

**Comment by tkrop** [comment]
Thanks for the response and the advice :)

**Comment by slonopotamus** [comment]
For the reference, this bug was introduced in commit 87b135d61aa12d8706b9b00fcaca75d6bda36a88.
