### ISSUE TITLE
Backend cannot be loaded

### ISSUE THREAD

**Issue by notklaatu** [asciidoctor/asciidoctor-epub3#444]
I've tried this on both Slackware Linux and RHEL 9.2, not sure what I'm doing wrong.

I install asciidoctor-epub3 with `gem`:

```
$ gem install asciidoctor-epub3
```

Then I try to use it:

```
$ asciidoctor --backend asciidoctor-epub3 -r ~/bin/asciidoctor-epub3 book.adoc --trace
<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- /home/klaatu/bin/asciidoctor-epub3 (LoadError)
        from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/share/gems/gems/asciidoctor-2.0.15/lib/asciidoctor/cli/options.rb:277:in `block in parse!'
        from /usr/share/gems/gems/asciidoctor-2.0.15/lib/asciidoctor/cli/options.rb:275:in `each'
        from /usr/share/gems/gems/asciidoctor-2.0.15/lib/asciidoctor/cli/options.rb:275:in `parse!'
        from /usr/share/gems/gems/asciidoctor-2.0.15/lib/asciidoctor/cli/options.rb:34:in `parse!'
        from /usr/share/gems/gems/asciidoctor-2.0.15/lib/asciidoctor/cli/invoker.rb:24:in `initialize'
        from /usr/share/gems/gems/asciidoctor-2.0.15/bin/asciidoctor:13:in `new'
        from /usr/share/gems/gems/asciidoctor-2.0.15/bin/asciidoctor:13:in `<top (required)>'
        from /usr/bin/asciidoctor:23:in `load'
        from /usr/bin/asciidoctor:23:in `<main>'
```

I can confirm that the gem is installed:

```
$ file ~/bin/asciidoctor-epub3
/home/klaatu/bin/asciidoctor-epub3: Ruby script, ASCII text executable
```

I've tried a `gem update` but that fails to resolve the issue.
Am I missing some dependencies?

Standard backends (html5, docbook5, and so on) work as expected.

**Comment by mojavelinux** [comment]
If you installed the gem, and the system package installs it correctly, then the command should be `asciidoctor-epub3`. There is no need to specify the backend or the require path. The bin script does all that for you.

**Comment by notklaatu** [comment]
```
$ asciidoctor-epub3 book.adoc
```

Worked like a charm. 
I [obviously] had misunderstood the form a backend took.

Very cool, thanks!
