### ISSUE TITLE
no mobi file generated

### ISSUE THREAD

**Issue by sonovice** [asciidoctor/asciidoctor-epub3#6]
When trying to generate a MOBI file out of the sample book using
"asciidoctor-epub3 -D output -a ebook-format=kf8 sample-book.adoc",
only an epub file called "sample-book-kf8.epub" is generated.

The terminal output says
"Wrote MOBI to [...]/output/sample-book.mobi"
but this file is never generated.

Using: Asciidoctor 1.5.0, Ruby 1.9.3 and a freshly installed asciidoctor-epub3

**Comment by mraible** [comment]
If I use `ebook-format=kf8` with asciidoctor-gradle-plugin 1.5.2, I get a index-kf8.epub file, but not a .mobi file. Is it supposed to create a .mobi file? I can convert this to .mobi using the kindlegen command-line tool, but it doesn't happen automatically for me.

**Comment by mojavelinux** [comment]
Chances are it can't find the kindlegen command. It's possible to specify
an environment variable to specify the path but I need to look it up.

We didn't bundle kindlegen in the AsciidoctorJ EPUB3 jar because that's not
allowed.

**Comment by mraible** [comment]
Yes, it looks like JRuby can't find kindlegen:

```
Caused by: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- kindlegen
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:939)
	at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54)
	at RUBY.require(uri:classloader:/gems/polyglot-0.3.5/lib/polyglot.rb:65)
	at RUBY.distill_epub_to_mobi(uri:classloader:/gems/asciidoctor-epub3-1.5.0.alpha.4/lib/asciidoctor-epub3/packager.rb:459)
	at RUBY.package(uri:classloader:/gems/asciidoctor-epub3-1.5.0.alpha.4/lib/asciidoctor-epub3/packager.rb:449)
	at RUBY.write(uri:classloader:/gems/asciidoctor-epub3-1.5.0.alpha.4/lib/asciidoctor-epub3/converter.rb:37)
	at RUBY.write(uri:classloader:/gems/asciidoctor-1.5.2/lib/asciidoctor/document.rb:1051)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1504)
	at RUBY.convert_file(uri:classloader:/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1562)
	at RUBY.convertFile(<script>:68)
```

I have installed it as a gem with Ruby and JRuby and neither seems to work. I also have the downloaded binary in my PATH. 

```
$ kindlegen

*************************************************************
 Amazon kindlegen(MAC OSX) V2.9 build 1028-0897292
 A command line e-book compiler
 Copyright Amazon.com and its Affiliates 2014
*************************************************************

Usage : kindlegen [filename.opf/.htm/.html/.epub/.zip or directory] [-c0 or -c1 or c2] [-verbose] [-western] [-o <file name>]
Note:
   zip formats are supported for XMDF and FB2 sources
   directory formats are supported for XMDF sources
Options:
   -c0: no compression
   -c1: standard DOC compression
   -c2: Kindle huffdic compression
   -o <file name>: Specifies the output file name. Output file will be created in the same directory as that of input file. <file name> should not contain directory path.
   -verbose: provides more information during ebook conversion
   -western: force build of Windows-1252 book
   -releasenotes: display release notes
   -gif: images are converted to GIF format (no JPEG in the book)
   -locale <locale option> : To display messages in selected language
      en: English
      de: German
      fr: French
      it: Italian
      es: Spanish
      zh: Chinese
      ja: Japanese
      pt: Portuguese
      ru: Russian
      nl: Dutch
```

How do I install the gem so asciidoctor-epub3 can find it?

**Comment by mojavelinux** [comment]
The environment variable is `KINDLEGEN`. It's probably best to specify an absolute path (resolved in whatever way works best for you).

kindlegen isn't really a gem. It's more of a script that taps into `gem install` to download kindlegen. So basically it's really no different from just putting kindlegen somewhere and telling AsciidoctorJ EPUB3 where it is.

**Comment by mojavelinux** [comment]
After having worked with the kindlegen "gem" and not been all that happy with its behavior, I think we'll probably switch to having Asciidoctor EPUB3 go fetch kindlegen in the future so we have some control over it. This is simple using the uri-cache library.

**Comment by mojavelinux** [comment]
It's best not to have AsciidoctorJ depend on an external Ruby environment because then you're build becomes awkwardly system dependent. Of course, in this case, we have to depend on kindlegen, but you could have Gradle download it and stick it into the build directory.

Here's how the kindlegen does it: https://github.com/tdtds/kindlegen/blob/master/ext/kindlegen/extconf.rb

**Comment by mojavelinux** [comment]
I'm not sure how to set environment variables from Gradle, or if that is even possible. It seems we need to have some way to get environment variables passed to the Ruby environment in AsciidoctorJ. We could modify Asciidoctor EPUB3 so that it looks for a system property when in the JRuby environment.

Otherwise, you have to set the environment variable when you invoke Gradle.

```
KINDLEGEN=/path/to/kindlegen gradle asciidoctor
```

**Comment by mojavelinux** [comment]
>  I also have the downloaded binary in my PATH.

Asciidoctor EPUB3 doesn't look on the PATH.

**Comment by mraible** [comment]
I tried specifying KINDLEGEN before the command and it fails. If I run it w/o KINDLEGEN, I'm able to generate the .epub and then manually convert it using the `kindlegen` command. Here's the output from the failure.

```
± KINDLEGEN=/opt/tools/kindlegen/kindlegen ./gradlew asciidoctor --stacktrace
:asciidoctor
Passing through unknown backend: pdf
> Building 0% > :asciidoctorProcessing colophon...
Processing building-an-app-with-jhipster...
Processing jhipster-s-ui-components...
Processing jhipster-s-api-building-blocks...
Wrote KF8 to /Users/mraible/dev/jhipster-book/build/asciidoc/epub3/index-kf8.epub
Extracted KF8 to /Users/mraible/dev/jhipster-book/build/asciidoc/epub3/index-kf8

*************************************************************
 Amazon kindlegen(MAC OSX) V2.9 build 1028-0897292
 A command line e-book compiler
 Copyright Amazon.com and its Affiliates 2014
*************************************************************

Info(prcgen):I1047: Added metadata dc:Title        "The JHipster Mini-Book"
Info(prcgen):I1047: Added metadata dc:Date         "2015-10-29T06:00:00Z"
Info(prcgen):I1047: Added metadata dc:Creator      "Matt Raible"
Info(prcgen):I1047: Added metadata dc:Creator      "Asciidoctor"
Info(prcgen):I1047: Added metadata dc:Contributor  "Matt Raible"
Info(cssparser):I10004: @rules other than @import, @charset and @font-face are not supported.
Info(prcgen):I1002: Parsing files  0000010
Info(prcgen):I1016: Building enhanced PRC file
Info(prcgen):I1015: Building PRC file
Info(prcgen):I1006: Resolving hyperlinks
Warning(prcgen):W14001: Hyperlink not resolved:  /var/folders/ny/q46v25tn22x1s3dlsnn4wpd00000gs/T/mobi-xUYuqP/OEBPS/document-3063654.xhtml#Browsersync
Warning(prcgen):W14002: Some hyperlinks could not be resolved.
Info(pagemap):I8000: No Page map found in the book
Info(prcgen):I1045: Computing UNICODE ranges used in the book
Info(prcgen):I1046: Found UNICODE range: Basic Latin [20..7E]
Info(prcgen):I1046: Found UNICODE range: Latin-1 Supplement [A0..FF]
Info(prcgen):I1046: Found UNICODE range: General Punctuation - Windows 1252 [2018..201A]
Info(prcgen):I1046: Found UNICODE range: Enclosed Alphanumerics [2460..24FF]
Info(prcgen):I1046: Found UNICODE range: Dingbats [2700..27BF]
Info(prcgen):I1046: Found UNICODE range: Arrows [2190..21FF]
Info(prcgen):I1046: Found UNICODE range: Latin Extended-A [100..17F]
Info(prcgen):I1046: Found UNICODE range: Box Drawing [2500..257F]
Info(prcgen):I1017: Building PRC file, record count:   0000099
Info(prcgen):I1039: Final stats - text compressed to (in % of original size):  41.91%
Info(prcgen):I1040: The document identifier is: "The_JHipster_Mini-Book"
Info(prcgen):I1041: The file format version is V6
Info(prcgen):I1031: Saving PRC file
Info(prcgen):I1032: PRC built successfully
Info(prcgen):I1007: Resolving mediaidlinks
Info(prcgen):I1011: Writing mediaidlinks
Info(prcgen):I1009: Resolving guide items
Info(prcgen):I1017: Building PRC file, record count:   0000126
Info(prcgen):I1039: Final stats - text compressed to (in % of original size):  42.21%
Info(prcgen):I1041: The file format version is V8
Info(prcgen):I15000:  Approximate Standard Mobi Deliverable file size :   0005437KB
Info(prcgen):I15001:  Approximate KF8 Deliverable file size :   0005796KB
Info(prcgen):I1036: Mobi file built successfully
Wrote MOBI to /Users/mraible/dev/jhipster-book/build/asciidoc/epub3/index.mobi
:asciidoctor FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':asciidoctor'.
> Error running Asciidoctor

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':asciidoctor'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
Caused by: org.gradle.api.GradleException: Error running Asciidoctor
	at org.asciidoctor.gradle.AsciidoctorTask.processDocumentsAndResources(AsciidoctorTask.groovy:659)
	at org.asciidoctor.gradle.AsciidoctorTask.this$4$processDocumentsAndResources(AsciidoctorTask.groovy)
	at org.asciidoctor.gradle.AsciidoctorTask$this$4$processDocumentsAndResources.callCurrent(Unknown Source)
	at org.asciidoctor.gradle.AsciidoctorTask.processAsciidocSources(AsciidoctorTask.groovy:592)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 47 more
Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) private method `gsub' called for #<Asciidoctor::Epub3::Packager:0x34d28f93>
	at RUBY.postprocess_xhtml(uri:classloader:/gems/asciidoctor-epub3-1.5.0.alpha.4/lib/asciidoctor-epub3/packager.rb:305)
	at RUBY.block in add_content(uri:classloader:/gems/asciidoctor-epub3-1.5.0.alpha.4/lib/asciidoctor-epub3/packager.rb:250)
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1560)
	at org.jruby.RubyEnumerable.each_with_index(org/jruby/RubyEnumerable.java:1016)
	at RUBY.block in add_content(uri:classloader:/gems/asciidoctor-epub3-1.5.0.alpha.4/lib/asciidoctor-epub3/packager.rb:248)
	at org.jruby.RubyBasicObject.instance_eval(org/jruby/RubyBasicObject.java:1633)
	at RUBY.block in ordered(uri:classloader:/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:40)
	at RUBY.ordered(uri:classloader:/gems/gepub-0.6.9.2/lib/gepub/package.rb:166)
	at RUBY.ordered(uri:classloader:/gems/gepub-0.6.9.2/lib/gepub/book.rb:205)
	at RUBY.ordered(uri:classloader:/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:39)
	at RUBY.block in add_content(uri:classloader:/gems/asciidoctor-epub3-1.5.0.alpha.4/lib/asciidoctor-epub3/packager.rb:245)
	at org.jruby.RubyBasicObject.instance_eval(org/jruby/RubyBasicObject.java:1633)
	at RUBY.initialize(uri:classloader:/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:33)
	at RUBY.resources(uri:classloader:/gems/gepub-0.6.9.2/lib/gepub/builder.rb:292)
	at RUBY.add_content(uri:classloader:/gems/asciidoctor-epub3-1.5.0.alpha.4/lib/asciidoctor-epub3/packager.rb:240)
	at RUBY.block in package(uri:classloader:/gems/asciidoctor-epub3-1.5.0.alpha.4/lib/asciidoctor-epub3/packager.rb:422)
	at org.jruby.RubyBasicObject.instance_eval(org/jruby/RubyBasicObject.java:1633)
	at RUBY.initialize(uri:classloader:/gems/gepub-0.6.9.2/lib/gepub/builder.rb:185)
	at RUBY.package(uri:classloader:/gems/asciidoctor-epub3-1.5.0.alpha.4/lib/asciidoctor-epub3/packager.rb:340)
	at RUBY.write(uri:classloader:/gems/asciidoctor-epub3-1.5.0.alpha.4/lib/asciidoctor-epub3/converter.rb:37)
	at RUBY.write(uri:classloader:/gems/asciidoctor-1.5.2/lib/asciidoctor/document.rb:1051)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1504)
	at RUBY.convert_file(uri:classloader:/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1562)
	at RUBY.convertFile(<script>:68)


BUILD FAILED

Total time: 6 mins 48.703 secs
```

**Comment by mraible** [comment]
Actually, it looks like a .mobi file was created. The stacktrace threw me off.

**Comment by mojavelinux** [comment]
> private method `gsub' called for #<Asciidoctor::Epub3::Packager:0x34d28f93>

Private method? That clinches it for me that Asciidoctor EPUB3 isn't understanding the structure of your document correctly. It's this same reason the TOC isn't appearing. The spine document has to be only include files like this sample:

https://raw.githubusercontent.com/asciidoctor/asciidoctor-epub3/master/data/samples/sample-book.adoc

Though it could be something even more subtle than that. I'd have to see the document to know.

**Comment by mojavelinux** [comment]
As it turns out, this was happening because Gradle was running the converter on files other than the spine document. Since it didn't understand the structure of those files, it was passing invalid nodes to the packager, which lead to it calling `gsub` on something other than a string. We need to make the converter more robust so that it doesn't crash on documents it doesn't understand. In other words, it should recover as gracefully as it can.

**Comment by mojavelinux** [comment]
I'm going to close as the issues we've identified are covered by other open issues.

Also, the kindlegen gem seems to be getting more attention now, so I think we can continue depending on it for the time being.
